wallet:
  mnemonic: velvet borrow tone ice outer sock humor vault coast drastic number cannon flower grass arrange shoulder victory cover thought exercise type camp submit fit

contracts:
  - name: counter
    codeId: 38015,
    address: terra184ujwgdt7py67mjktegemsd6fs6gt8s0m6vjup